services:
  - type: web
    name: adora-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: TEMP_DIR
        value: ./temp
      - key: FILE_TTL_MINUTES
        value: 10
      - key: MAX_CONCURRENT_DOWNLOADS
        value: 3
